### ISSUE TITLE
bug: compatibleRuntime issue on serverless v4

### ISSUE THREAD

**Issue by AndrewBarba** [serverless-bun/serverless-bun#35]
I recently started getting a weird error from serverless v4 that I cannot track down:

```
ServerlessError3: An error occurred: BunLambdaLayer - Resource handler returned 
message: "1 validation error detected: Value '[null, provided.al2, provided]' 
at 'compatibleRuntimes' failed to satisfy constraint: Member must satisfy enum 
value set: [nodejs20.x, provided.al2023, python3.12, python3.13, nodejs22.x, 
java17, nodejs16.x, dotnet8, python3.10, java11, python3.11, dotnet6, java21, 
nodejs18.x, provided.al2, ruby3.3, java8.al2, ruby3.2, python3.8, python3.9]
```

Do you have any idea where this could be coming from? It's saying the type for `compatibleRuntimes` is: 

```[null, provided.al2, provided]``` 

but inside this package I only see refs to:

```[provided.al2023, provided.al2, provided]```

**Comment by junwen-k** [comment]
Hi, and thanks for reporting the issue!

Could you provide a minimal reproducible example, or perhaps share your `serverless.yml`? It would help with debugging and identifying the problem more easily.

One thing to check is whether the issue might be related to overrides at the function level, such as:

```yml
# ...

functions:
  myFunction:
    architecture: arm64
    runtime: null # or could it be an accidental variable assignment resolving to `null` here?
```
